export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const SAVE_USER_INFO_SUCCESS = 'SAVE_USER_INFO_SUCCESS';
export const SAVE_USER_INFO_ERROR = 'SAVE_USER_INFO_ERROR';
export const CLEAN_STORE = 'CLEAN_STORE';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SAVE_MESSAGES = 'SAVE_MESSAGE';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const SAVE_CUSTOMERS = 'SAVE_CUSTOMER';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DEL_NOTIFICATION = 'DEL_NOTIFICATION';
export const CLEAN_NOTIFICATION = 'CLEAN_NOTIFICATION';
